version: '3.8'

services:
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE= school
      - MYSQL_USER= root
      - MYSQL_PASSWORD= sync@7867
      - MYSQL_ROOT_PASSWORD= sync@7867
    volumes:
      - db-data: /var/lib/mysql  




volumes:
  db-data: ~

