[build]
builder = "NIXPACKS"
watchPatterns = ["attendance-management"]

[deploy]
numReplicas = 1
startCommand = "php artisan migrate --force"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
