[build]
builder = "NIXPACKS"
buildCommand="composer install --no-interaction --prefer-dist && php artisan config:clear && php artisan optimize && php artisan migrate --force"
watchPatterns = ["/"]

[deploy]
numReplicas = 1
startCommand="php artisan serve"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
