[build]
runtime = "php"
build = "composer install --no-interaction --prefer-dist && php artisan optimize"
root = "E:\\Development\\htdocs\\School"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=8080" # This is the start command for Laravel's built-in development server


