[build]
builder = "NIXPACKS"
nixpacksPlan = {"repo"="Ridwanur786/attendance-management"}
watchPatterns = ["attendance-management"]

[deploy]
numReplicas = 1
startCommand = "php artisan migrate --force"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
