[build]
  runtime = "php"
  build = "composer install --no-interaction --prefer-dist && php artisan optimize"
  root = "E:\\Development\\htdocs\\School"

[deploy]
  numReplicas = 1
  startCommand = "php artisan serve"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[watch]
  paths = ["E:\\Development\\htdocs\\School"]
