[build]
  builder = "NIXPACKS"
  build = "composer install --no-interaction --prefer-dist && php artisan optimize"
  root = "E:\\Development\\htdocs\\School"

[deploy]
  numReplicas = 1
  startCommand = "php artisan serve"  # Or the appropriate command for your web server
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
